# Generated by Django 5.1.7 on 2025-03-12 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название модуля', max_length=150, verbose_name='Образовательный модуль')),
                ('description', models.TextField(help_text='Введите описание модуля', verbose_name='Описание образовательного модуля')),
                ('owner', models.ForeignKey(blank=True, help_text='Выберите владельца модуля', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Образовательный модуль',
                'verbose_name_plural': 'Образовательные модули',
            },
        ),
    ]
