# Generated by Django 5.1.7 on 2025-03-16 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmodule',
            name='owner',
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание модуля', null=True, verbose_name='Описание образовательного модуля'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='name',
            field=models.CharField(help_text='Введите название модуля', max_length=150, verbose_name='Название образовательного модуля'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название темы', max_length=150, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, help_text='Введите описание темы', null=True, verbose_name='Описание темы')),
                ('educational_module', models.ForeignKey(help_text='Выберите модуль', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='educational_modules.educationalmodule', verbose_name='Образовательный модуль')),
            ],
            options={
                'verbose_name': 'Образовательная тема',
                'verbose_name_plural': 'Образовательные темы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название урока', max_length=150, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание урока')),
                ('video_link', models.CharField(help_text='Добавьте ссылку на урок', max_length=255, verbose_name='Ссылка на урок')),
                ('owner', models.ForeignKey(blank=True, help_text='Выберите автора урока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Автор урока')),
                ('topic', models.ForeignKey(help_text='Выберите образовательную тему', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='educational_modules.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
