# Generated by Django 5.1.7 on 2025-03-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_modules', '0002_remove_educationalmodule_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Выберите образовательную тему', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='educational_modules.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='educational_module',
            field=models.ForeignKey(blank=True, help_text='Выберите модуль', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='educational_modules.educationalmodule', verbose_name='Образовательный модуль'),
        ),
    ]
